// Automatically generated by bindings.c. DO NOT EDIT.

#include <string_view>
#include <span>
#include <frc/smartdashboard/SmartDashboard.h>
#include <frc/smartdashboard/SendableChooser.h>
#include <frc/smartdashboard/Field2d.h>

#include "luadef.h"

LUAFUNC bool ContainsKey(const char * key) {
    auto _result = frc::SmartDashboard::ContainsKey((std::string_view)key);
    return (bool)_result;
}

LUAFUNC void SetPersistent(const char * key) {
    frc::SmartDashboard::SetPersistent((std::string_view)key);
}

LUAFUNC void ClearPersistent(const char * key) {
    frc::SmartDashboard::ClearPersistent((std::string_view)key);
}

LUAFUNC bool IsPersistent(const char * key) {
    auto _result = frc::SmartDashboard::IsPersistent((std::string_view)key);
    return (bool)_result;
}

LUAFUNC void PutBoolean(const char * keyName, bool value) {
    frc::SmartDashboard::PutBoolean((std::string_view)keyName, value);
}

LUAFUNC bool GetBoolean(const char * keyName, bool defaultValue) {
    auto _result = frc::SmartDashboard::GetBoolean((std::string_view)keyName, defaultValue);
    return (bool)_result;
}

LUAFUNC void PutNumber(const char * keyName, double value) {
    frc::SmartDashboard::PutNumber((std::string_view)keyName, value);
}

LUAFUNC double GetNumber(const char * keyName, double defaultValue) {
    auto _result = frc::SmartDashboard::GetNumber((std::string_view)keyName, defaultValue);
    return (double)_result;
}

LUAFUNC void PutString(const char * keyName, const char * value) {
    frc::SmartDashboard::PutString((std::string_view)keyName, (std::string_view)value);
}

LUAFUNC const char * GetString(const char * keyName, const char * defaultValue) {
	return stdStringForLua(frc::SmartDashboard::GetString((std::string_view)keyName, (std::string_view)defaultValue));
}

LUAFUNC void PutBooleanArray(const char * keyName, int * value, size_t size) {
	frc::SmartDashboard::PutBooleanArray((std::string_view)keyName, std::span(value, size));
}

LUAFUNC size_t GetBooleanArraySize(const char * keyName) {
	return frc::SmartDashboard::GetBooleanArray(keyName, {}).size();
}

LUAFUNC int * GetBooleanArray(const char * keyName, int * defaultValue, size_t defaultSize) {
	return frc::SmartDashboard::GetBooleanArray((std::string_view)keyName, std::span(defaultValue, defaultSize)).data();
}

LUAFUNC void PutNumberArray(const char * keyName, double * value, size_t size) {
	frc::SmartDashboard::PutNumberArray((std::string_view)keyName, std::span(value, size));
}

LUAFUNC size_t GetNumberArraySize(const char * keyName) {
	return frc::SmartDashboard::GetNumberArray(keyName, {}).size();
}

LUAFUNC double * GetNumberArray(const char * keyName, double * defaultValue, size_t defaultSize) {
	return frc::SmartDashboard::GetNumberArray((std::string_view)keyName, std::span(defaultValue, defaultSize)).data();
}

LUAFUNC void PutStringArray(const char * keyName, const char ** value, size_t size) {
	std::vector<std::string> strVec(value, value + size);
	frc::SmartDashboard::PutStringArray((std::string_view)keyName, std::span<std::string>(strVec));
}

LUAFUNC void PutIntChooser(const char * key, void * data) {
    frc::SmartDashboard::PutData((std::string_view)key, (frc::SendableChooser<int>*)data);
}

LUAFUNC void PutField(void * field) {
    frc::SmartDashboard::PutData((frc::Field2d*)field);
}

LUAFUNC void* SendableChooser_new() {
    return new frc::SendableChooser<int>();
}

LUAFUNC void SendableChooser_AddOption(void* _this, const char * name, int object) {
    ((frc::SendableChooser<int>*)_this)
        ->AddOption((std::string_view)name, object);
}

LUAFUNC int SendableChooser_GetSelected(void* _this) {
    auto _result = ((frc::SendableChooser<int>*)_this)
        ->GetSelected();
    return (int)_result;
}

LUAFUNC void* Field2d_new() {
    return new frc::Field2d();
}

LUAFUNC void Field2d_SetRobotPose(void* _this, double x, double y, double rotation) {
    ((frc::Field2d*)_this)
        ->SetRobotPose(units::inch_t(x), units::inch_t(y), units::radian_t(rotation));
}
