// Automatically generated by gen_bindings.lua. DO NOT EDIT.

#include <frc/Filesystem.h>

#include "luadef.h"

LUAFUNC const char* GetDeployDirectory() {
return stdStringForLua(frc::filesystem::GetDeployDirectory());
}
