-- Automatically generated by gen_bindings.lua. DO NOT EDIT.

local ffi = require("ffi")
require("wpilib.bindings.asserts")
require("wpilib.bindings.enum")

---@class CameraServer
---@field _this CameraServer
CameraServer = {}

function CameraServer:startAutomaticCapture()
    ffi.C.StartAutomaticCapture()
end
