-- Automatically generated by gen_bindings.lua. DO NOT EDIT.

local ffi = require("ffi")
require("wpilib.bindings.asserts")
require("wpilib.bindings.enum")

---@class SwerveDriveKinematics
---@field _this SwerveDriveKinematics
SwerveDriveKinematics = {}

---@param flx number
---@param fly number
---@param frx number
---@param fry number
---@param blx number
---@param bly number
---@param brx number
---@param bry number
---@return SwerveDriveKinematics
function SwerveDriveKinematics:new(flx, fly, frx, fry, blx, bly, brx, bry)
    flx = AssertNumber(flx)
    fly = AssertNumber(fly)
    frx = AssertNumber(frx)
    fry = AssertNumber(fry)
    blx = AssertNumber(blx)
    bly = AssertNumber(bly)
    brx = AssertNumber(brx)
    bry = AssertNumber(bry)
    local instance = {
        _this = ffi.C.SwerveDriveKinematics_new(flx, fly, frx, fry, blx, bly, brx, bry),
    }
    setmetatable(instance, self)
    self.__index = self
    return instance
end

---@param vx number
---@param vy number
---@param vr number
---@return any
function SwerveDriveKinematics:toSwerveModuleStates(vx, vy, vr)
    vx = AssertNumber(vx)
    vy = AssertNumber(vy)
    vr = AssertNumber(vr)
    return ffi.C.SwerveDriveKinematics_ToSwerveModuleStates(self._this, vx, vy, vr)
end
